// Fix-plugin loader: scaffold, verify, snapshot, and revert the
// plugin directories the evolve loop produces under .flavor/plugins/.
//
// verifyFixPlugin runs the plugin in an isolated Worker thread sandbox so that
// activation and contribution registration can be checked WITHOUT
// touching the real host's hooks/tools/commands and without giving the plugin
// access to the host process (no filesystem, no network, no shared memory).

import { cp, mkdir, mkdtemp, readdir, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

import { PluginHost } from "../plugins/host.js";

export const PLUGIN_DIR = join(".flavor", "plugins");
export const VERSIONS_DIR = join(".flavor", "plugins", ".versions");

/** Sanitize a tool name into a valid fix-plugin dir name (letters/digits/-). */
export function sanitizePluginName(tool: string): string {
  const base = String(tool ?? "fix").replace(/[^a-z0-9-]/gi, "-").toLowerCase();
  return base.startsWith("fix-") ? base : `fix-${base}`;
}

export function fixPluginDir(workspace: string, name: string): string {
  return resolve(workspace, PLUGIN_DIR, name);
}

function versionsDirFor(workspace: string, name: string): string {
  return resolve(workspace, VERSIONS_DIR, name);
}

function timestamp(): string {
  return new Date().toISOString().replaceAll(":", "-");
}

const SCAFFOLD_MANIFEST = (name: string): string => JSON.stringify({
  name,
  version: "0.1.0",
  apiVersion: "1",
  main: "index.js",
  permissions: [],
  contributes: { commands: [], tools: [], hooks: [], skillRoots: [], modelAdapters: [] },
}, null, 2);

const SCAFFOLD_ENTRY = (name: string): string => `// ${name} — generated by /evolve improve <suggestionId>.
// flavor-code plugin contract:
//   - manifest: flavor-plugin.json (apiVersion "1", main entry, declared contributes)
//   - entry must export \`activate(context)\`
//   - context: { signal, config, logger, services, registerCommand,
//                registerTool, registerHook, registerSkillRoot, registerModelAdapter }
//   - every contribution you register MUST be declared in contributes
//   - sandbox verification only permits relative JS modules inside this plugin root;
//     Node.js built-ins, package imports, filesystem, and network APIs are unavailable
//
// Implement your fix here. Example — observe tool failures:
//   ctx.registerHook("PostToolUseFailure", (event) => {
//     ctx.logger.info(\`observed: \${event.payload.tool}\`);
//     return { decision: "allow" };
//   });
export function activate(ctx) {
  // TODO: implement the fix, then run /evolve verify ${name} to dry-run it.
}
`;

/** Scaffold a fix-plugin directory (idempotent — never overwrites existing work). */
export async function scaffoldFixPlugin(workspace: string, name: string): Promise<string> {
  const dir = fixPluginDir(workspace, name);
  await mkdir(dir, { recursive: true });
  const manifestPath = join(dir, "flavor-plugin.json");
  const entryPath = join(dir, "index.js");
  try {
    await writeFile(manifestPath, SCAFFOLD_MANIFEST(name), { encoding: "utf8", flag: "wx" });
    await writeFile(entryPath, SCAFFOLD_ENTRY(name), { encoding: "utf8", flag: "wx" });
  } catch (error) {
    if (typeof error === "object" && error !== null && "code" in error && (error as Record<string, unknown>).code === "EEXIST") {
      // Already scaffolded; keep whatever the agent has written there.
    } else {
      throw error;
    }
  }
  return dir;
}

export interface FixPluginVerifyReport {
  ok: boolean;
  /** "name@version" of the loaded plugin. */
  provided: string[];
  tools: string[];
  commands: string[];
  error?: string;
}

/** Verify a plugin in an isolated Worker sandbox. The real host is untouched. */
export async function verifyFixPlugin(workspace: string, name: string): Promise<FixPluginVerifyReport> {
  const pluginRoot = fixPluginDir(workspace, name);
  try {
    await stat(pluginRoot);
  } catch {
    return { ok: false, provided: [], tools: [], commands: [], error: `Plugin "${name}" not found.` };
  }
  const collected = { tools: [] as string[], commands: [] as string[] };
  const sandbox = await mkdtemp(join(tmpdir(), "flavor-evolve-verify-"));
  try {
    await cp(pluginRoot, join(sandbox, name), { recursive: true });
    const host = new PluginHost({
      projectPluginDirs: [sandbox],
      sandbox: true,
      config: {},
      activationTimeoutMs: 5_000,
      registrations: {
        command: (commandName) => { collected.commands.push(commandName); return () => undefined; },
        tool: (toolName) => { collected.tools.push(toolName); return () => undefined; },
        hook: () => () => undefined,
        skillRoot: () => () => undefined,
        modelAdapter: () => () => undefined,
      },
      logger: { debug() {}, info() {}, warn() {}, error() {} },
    });
    await host.loadAll();
    const loaded = host.loadedPlugins;
    const diagnostics = host.diagnostics;
    await host.unloadAll();
    const error = diagnostics[0]?.message;
    return {
      ok: diagnostics.length === 0 && loaded.length === 1,
      provided: loaded.map((plugin) => `${plugin.name}@${plugin.version}`),
      tools: collected.tools,
      commands: collected.commands,
      ...(error === undefined ? {} : { error }),
    };
  } catch (error) {
    return {
      ok: false,
      provided: [],
      tools: collected.tools,
      commands: collected.commands,
      error: error instanceof Error ? error.message : String(error),
    };
  } finally {
    await rm(sandbox, { recursive: true, force: true });
  }
}

/** Copy the current plugin dir into .versions/<name>/<timestamp>/. */
export async function snapshotFixPlugin(workspace: string, name: string): Promise<string> {
  const pluginRoot = fixPluginDir(workspace, name);
  const snapshotRoot = join(versionsDirFor(workspace, name), timestamp());
  await mkdir(snapshotRoot, { recursive: true });
  await cp(pluginRoot, snapshotRoot, { recursive: true });
  return snapshotRoot;
}

/** Restore the latest good snapshot of a plugin dir. */
export async function revertFixPlugin(workspace: string, name: string): Promise<string> {
  const pluginRoot = fixPluginDir(workspace, name);
  try {
    await stat(pluginRoot);
  } catch {
    throw new Error(`Plugin "${name}" not found.`);
  }
  const versionsRoot = versionsDirFor(workspace, name);
  let entries: string[];
  try {
    entries = await readdir(versionsRoot);
  } catch {
    throw new Error(`Plugin "${name}" has no snapshot to restore.`);
  }
  const snapshots = entries.filter((entry) => !entry.startsWith(".")).sort();
  if (snapshots.length === 0) throw new Error(`Plugin "${name}" has no snapshot to restore.`);
  const latest = join(versionsRoot, snapshots[snapshots.length - 1]!);
  await rm(pluginRoot, { recursive: true, force: true });
  await mkdir(pluginRoot, { recursive: true });
  await cp(latest, pluginRoot, { recursive: true });
  return `Restored "${name}" from ${snapshots[snapshots.length - 1]}.`;
}
