export const DESKTOP_CHANNELS = {
  bootstrap: "desktop:bootstrap",
  chooseWorkspace: "desktop:choose-workspace",
  openWorkspace: "desktop:open-workspace",
  startSession: "desktop:start-session",
  deleteSession: "desktop:delete-session",
  showAppMenu: "desktop:show-app-menu",
  submit: "desktop:submit",
  interrupt: "desktop:interrupt",
  resolveApproval: "desktop:resolve-approval",
  answerQuestions: "desktop:answer-questions",
  listFiles: "desktop:list-files",
  listSkills: "desktop:list-skills",
  getSkill: "desktop:get-skill",
  createSkill: "desktop:create-skill",
  updateSkill: "desktop:update-skill",
  deleteSkill: "desktop:delete-skill",
  setSkillEnabled: "desktop:set-skill-enabled",
  switchModel: "desktop:switch-model",
  addModel: "desktop:add-model",
  event: "desktop:event",
} as const;
