import { describe, expect, it, vi } from "vitest";

import { isLoopbackPreviewUrl, parseInteractionManifest, runInteractionManifest, type D2cInteractionDriver } from "../../src/d2c/interaction.js";

const raw = JSON.stringify({ schemaVersion: 1, product: "Demo", deterministic: true, pages: [{ url: "orders.html", scenarios: [{ id: "orders-filter", steps: [
  { action: "fill", selector: "#search", value: "PO-1" },
  { expect: "count", selector: "#rows tr", value: 1 },
] }] }] });

describe("D2C interaction acceptance", () => {
  it("validates deterministic manifests and rejects unsafe page URLs", () => {
    expect(parseInteractionManifest(raw).pages[0]?.scenarios[0]?.id).toBe("orders-filter");
    expect(() => parseInteractionManifest(JSON.stringify({ schemaVersion: 1, product: "x", deterministic: true,
      pages: [{ url: "https://evil.example/", scenarios: [] }] }))).toThrow(/url|page/i);
    expect(() => parseInteractionManifest(JSON.stringify({ schemaVersion: 1, product: "x", deterministic: false, pages: [] }))).toThrow(/deterministic/i);
    for (const url of ["../secrets.html", "/absolute.html", "foo\\bar.html", "#fragment", "http://localhost:1/x"]) {
      expect(() => parseInteractionManifest(JSON.stringify({ schemaVersion: 1, product: "x", deterministic: true,
        pages: [{ url, scenarios: [] }] }))).toThrow();
    }
  });

  it("supports semantic select, value and same-origin URL steps for autonomous journeys", () => {
    const manifest = parseInteractionManifest(JSON.stringify({ schemaVersion: 1, product: "filters", deterministic: true,
      pages: [{ url: "orders.html", scenarios: [{ id: "filter-and-open", steps: [
        { action: "select", selector: "#status", value: "pending" },
        { expect: "value", selector: "#status", value: "pending" },
        { action: "click", selector: "#detail" },
        { expect: "url", value: "orders/detail.html" },
      ] }] }],
    }));
    expect(manifest.pages[0]?.scenarios[0]?.steps).toHaveLength(4);
  });

  it("normalizes safe model-authored manifest metadata and wait steps", () => {
    const manifest = parseInteractionManifest(JSON.stringify({
      schemaVersion: 1, product: "legacy prototype", deterministic: true, notes: "generated by model",
      pages: [{ url: "index.html", title: "首页", scenarios: [{ id: "open-detail", title: "打开详情", steps: [
        { action: "click", selector: "#open" },
        { action: "wait", ms: 450 },
        { expect: "url", selector: "body", value: "detail.html" },
      ] }] }],
    }));
    expect(manifest).toEqual({
      schemaVersion: 1, product: "legacy prototype", deterministic: true,
      pages: [{ url: "index.html", scenarios: [{ id: "open-detail", steps: [
        { action: "click", selector: "#open" },
        { action: "wait", ms: 450 },
        { expect: "url", value: "detail.html" },
      ] }] }],
    });
  });

  it("normalizes model-authored API lists and expectation aliases", () => {
    const manifest = parseInteractionManifest(JSON.stringify({
      schemaVersion: 1, product: "inventory", deterministic: true,
      pages: [{ url: "index.html#/products", requireApi: ["GET /api/products"], scenarios: [{
        id: "filter-products", requireApi: ["GET /api/products"], steps: [
          { action: "expect", type: "visible", selector: "#products" },
          { action: "expect", type: "attribute", selector: "#menu", attribute: "aria-expanded", value: "true" },
          { action: "expect", type: "url", selector: "body", value: "#/products" },
        ],
      }] }],
    }));

    expect(manifest.pages[0]).toEqual({
      url: "index.html#/products", requireApi: true, scenarios: [{
        id: "filter-products", requireApi: true, steps: [
          { expect: "visible", selector: "#products" },
          { expect: "attribute", selector: "#menu", name: "aria-expanded", value: "true" },
          { expect: "url", value: "index.html#/products" },
        ],
      }],
    });
  });

  it("normalizes expectation names emitted directly in the action field", () => {
    const expectationSteps = [
      { action: "visible", selector: "#dialog" },
      { action: "hidden", selector: "#loading" },
      { action: "not-exists", selector: "#deleted" },
      { action: "text", selector: "#total", value: "13" },
      { action: "text-contains", selector: "#toast", value: "成功" },
      { action: "class", selector: "#tab", value: "active" },
      { action: "count", selector: ".row", value: 10 },
      { action: "value", selector: "#query", value: "" },
      { action: "url", value: "index.html#/products" },
    ];
    const manifest = parseInteractionManifest(JSON.stringify({
      schemaVersion: 1, product: "inventory", deterministic: true,
      pages: [{ url: "index.html#/products", scenarios: [{ id: "generated-aliases", requireApi: false, steps: expectationSteps }] }],
    }));

    expect(manifest.pages[0]?.scenarios[0]?.steps).toEqual(expectationSteps.map(({ action, ...step }) => ({
      expect: action, ...step,
    })));
  });

  it("accepts route opening, field blur and hidden-state evidence from generated journeys", () => {
    const manifest = parseInteractionManifest(JSON.stringify({
      schemaVersion: 1, product: "inventory", deterministic: true,
      pages: [{ url: "index.html#/products", scenarios: [{ id: "create-product", title: "新建商品", steps: [
        { action: "open", url: "index.html#/products" },
        { action: "fill", selector: "#f-sku", value: "SKU-001" },
        { action: "blur", selector: "#f-sku" },
        { expect: "hidden", selector: "#product-dialog" },
        { expect: "not-exists", selector: "#settings-dirty" },
      ] }] }],
    }));
    expect(manifest.pages[0]?.scenarios[0]?.steps).toEqual([
      { action: "open", url: "index.html#/products" },
      { action: "fill", selector: "#f-sku", value: "SKU-001" },
      { action: "blur", selector: "#f-sku" },
      { expect: "hidden", selector: "#product-dialog" },
      { expect: "not-exists", selector: "#settings-dirty" },
    ]);
  });

  it("still rejects unsafe or incomplete steps with a concise path", () => {
    expect(() => parseInteractionManifest(JSON.stringify({
      schemaVersion: 1, product: "broken", deterministic: true,
      pages: [{ url: "index.html", scenarios: [{ id: "broken", steps: [{ action: "click" }] }] }],
    }))).toThrow(/pages\.0\.scenarios\.0\.steps\.0/i);
  });

  it("permits only loopback HTTP preview addresses", () => {
    expect(isLoopbackPreviewUrl("http://127.0.0.1:4173/")).toBe(true);
    expect(isLoopbackPreviewUrl("http://localhost:5173/orders.html")).toBe(true);
    expect(isLoopbackPreviewUrl("https://127.0.0.1:4173/")).toBe(false);
    expect(isLoopbackPreviewUrl("http://0.0.0.0:4173/")).toBe(false);
    expect(isLoopbackPreviewUrl("http://example.com/")).toBe(false);
    expect(isLoopbackPreviewUrl("http://user:pass@localhost:4173/")).toBe(false);
    expect(isLoopbackPreviewUrl("not a url")).toBe(false);
  });

  it("executes actions and assertions and requires observable API traffic", async () => {
    const actions: unknown[] = [];
    const driver: D2cInteractionDriver = {
      load: vi.fn(async () => undefined),
      action: vi.fn(async (step) => { actions.push(step); }),
      assertion: vi.fn(async () => ({ passed: true })),
      apiRequestCount: () => 1,
      close: vi.fn(async () => undefined),
    };
    const result = await runInteractionManifest(parseInteractionManifest(raw), "http://127.0.0.1:4173/", async () => driver);
    expect(result).toMatchObject({ passed: true, total: 1, failures: 0, apiRequestCount: 1 });
    expect(result.scenarios[0]).toMatchObject({ id: "orders-filter", pageUrl: "http://127.0.0.1:4173/orders.html", passed: true });
    expect(actions).toHaveLength(1);
    expect(driver.close).toHaveBeenCalledOnce();
  });

  it("reports assertion failures, driver errors and static pages without API calls", async () => {
    const results = await Promise.all([
      runInteractionManifest(parseInteractionManifest(raw), "http://localhost:4173/", async () => ({
        load: async () => undefined, action: async () => undefined,
        assertion: async () => ({ passed: false, actual: "0" }), apiRequestCount: () => 1, close: async () => undefined,
      })),
      runInteractionManifest(parseInteractionManifest(raw), "http://localhost:4173/", async () => ({
        load: async () => undefined, action: async () => { throw new Error("element missing"); },
        assertion: async () => ({ passed: true }), apiRequestCount: () => 1, close: async () => undefined,
      })),
      runInteractionManifest(parseInteractionManifest(raw), "http://localhost:4173/", async () => ({
        load: async () => undefined, action: async () => undefined,
        assertion: async () => ({ passed: true }), apiRequestCount: () => 0, close: async () => undefined,
      })),
    ]);
    expect(results[0]?.scenarios[0]?.failure).toMatch(/expected|actual/i);
    expect(results[1]?.scenarios[0]?.failure).toContain("element missing");
    expect(results[2]?.scenarios[0]?.failure).toMatch(/api/i);
    expect(results.every((item) => !item.passed)).toBe(true);
  });

  it("creates an isolated driver per scenario and supports explicitly static scenarios", async () => {
    const manifest = parseInteractionManifest(JSON.stringify({
      schemaVersion: 1, product: "mixed", deterministic: true,
      pages: [{ url: "index.html", requireApi: false, scenarios: [
        { id: "keyboard", steps: [{ action: "key", value: "Escape" }, { expect: "visible", selector: "main" }] },
        { id: "hover", requireApi: true, steps: [{ action: "hover", selector: "button" }, { expect: "class", selector: "button", value: "active" }] },
      ] }],
    }));
    const closes: Array<ReturnType<typeof vi.fn>> = [];
    let created = 0;
    const result = await runInteractionManifest(manifest, "http://localhost:5173/", async () => {
      created += 1;
      const close = vi.fn(async () => undefined); closes.push(close);
      return { load: async () => undefined, action: async () => undefined, assertion: async () => ({ passed: true }),
        apiRequestCount: () => created === 1 ? 0 : 2, close };
    });
    expect(result).toMatchObject({ passed: true, total: 2, failures: 0, apiRequestCount: 2 });
    expect(created).toBe(2);
    expect(closes.every((close) => close.mock.calls.length === 1)).toBe(true);
  });
});
